server:
  port: 18081

spring:
  application:
    name: contais-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Contais/contais-repo/
#          search-paths: contais-config-repo

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:18080/eureka