server:
  port: 18181

spring:
  application:
    name: contais-order
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.230:8848
    sentinel:
      transport:
        dashboard: http://192.168.3.230:8858
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
